### PR TITLE
V5.3.3

### PR DESCRIPTION
**Pull request by DustinGrau**
**Resolved Issues:**
#354 
#358 
#359 
#360 
#361 

**Ghosts Busted:**
- Fixed 1984 bootup sound having inverted stereo channels
- Fixed 84/89 outer cyclotron LED fade timings
- Fixed 84/89 outer cyclotron overheat animation
- Fixed 84/89 outer cyclotron strobing in Holiday/Spectral modes
- Fixed Frutto inner cyclotron panel LED mode indicator colors
- Fixed music quick volume adjustment only working on standalone wands
- Fixed pack sound overlap when recovering from overheat
- Fixed spectral custom color not being obeyed while brass pack effects are active
- Fixed wand sound overlap when recovering from button mashing
- Fixed wand sound overlap when recovering from overheat
- Fixed web interface buttons ignoring pack state
- Fixed web interface not allowing overheat if no wand is connected
- Fixed web interface not allowing smoke settings to be set if no wand is connected
- Many "under the hood" fixes and optimizations

**New Features:**
- Support for the new Frutto Current Sensor for stock wands
- Support for Single Shot Compact Thrower
- New barrel pop sound for 84/89 thanks to Graham Starke
- New brass pack shutdown sound thanks to @Aces6469
- New static color mode for Frutto inner cyclotron LED panel for users with prop-accurate colored cliplites
- Initial implementation for #341 
- Inner cyclotron LED panel will now remain off while brass pack effects are active
- Wand can now be switched to standalone mode by jumping the pack serial connector on the wand PCB
- Updated documentation
- Updated web interface

This release requires updating of all 3 devices (pack, wand, wireless/attenuator) and updating of sound effects for your SD cards.

### CODE REVIEW

**Comment by DustinGrau** [comment]
PR created, started working on the bugfix list but could use some help there @nomakewan 
If you look at the format you can see that it's possible to reference a bug number by just hashtag and numeric ID

**Comment by nomakewan** [comment]
Just tossed in one last fix since it was easy to do. I'm going to write up a text-based changelog on my end and then adapt it to the PR format per your request. Stand by!

**Review by nomakewan — APPROVED** [review]
Changes all look great on my end. My pack demo seems to be working well and the web functions all work as expected even without a wand connected.

I'm going to run a few final quick tests on my bench wand just to be sure but I'm slapping my seal of approval on this PR.

**Comment by DustinGrau** [comment]
I ran out of time for testing this morning, I need to go make sure some theater students don't cut their fingers off in the woodshop, so I will try to get to testing on my stuff later today.

**Review by gpstar81 — APPROVED** [review]

**Comment by DustinGrau** [comment]
Since everyone added their review and approval, I've just loaded up the latest and tested without any obvious issues. Calling this one done and ready for announcement when the support page can be updated.

**Pull request merged**
