### PR TITLE
V5.4.0

### PR DESCRIPTION
**Pull request by DustinGrau**
This is the last minor release version for the v5.x series of the software, containing significant fixes and enhancements for existing kit hardware. Work will begin to shift to the v6 release beyond this point so that we can support more advanced features requested from the community. This release contains a lot of code cleanup, but not as much as planned for the future 6.x series. At the very least the GPStar Audio Serial Library has been overhauled and cleaned up for a public release and is now available as an Arduino Library. This standardizes the code across all devices which utilize sound output.

Resolved Issues:
#368
#369
#372
#373
#374
#375
#376
#378
#379
#380
#382
#384
#385
#387
 
Ghosts Busted:
 
-Fixed Afterlife/Frozen Empire short startup outer cyclotron ramp speed
-Fixed Afterlife/Frozen Empire wand ramp-up sound mix bug
-Fixed Attenuator buzzer sound causing vibration motor to stop working
-Fixed Attenuator causing startup issue when switching on in Mode Original
-Fixed Attenuator not respecting user settings for vibration and overheat feedback
-Fixed Attenuator synchronization issues and improved synchronization speed
-Fixed barrel tip of Frutto barrel not lighting up in the EEPROM LED Menu
-Fixed colour transition speeds for Frutto barrel in spectral modes
-Fixed Frozen Empire freeze lockup pack lighting effects
-Fixed individual LED inner cyclotron switch panel not turning off when lid is on in a specific edge case
-Fixed ion arm switch causing shutdown sequence even if pack is not on
-Fixed ion arm switch/Attenuator/web UI not being able to turn pack on with Lite kits
-Fixed missing system voltage in text-based web interface
-Fixed music pause/resume function not working correctly
-Fixed non-addressable barrel LED not functioning correctly on Single Shot Blaster
-Fixed several issues relating to audio level calculations
-Fixed several instances of Frozen Empire SFX not being stopped/started properly
-Fixed several sound fade-in and loop parameters to sound more natural
-Fixed Single Shot Blaster inadvertently using button mash lockout code
-Fixed sound effect volume changes not immediately taking effect
-Fixed standalone wand TVG idle sounds being too quiet
-Fixed stereo channel mix for fire tail effects in 1984 and Afterlife so they sound correct on the wand
-Fixed vibration and year indicator LEDs sticking on when brass pack is running
-Fixed wand functions working before pack has finished POST sequence
-Fixed wand playing incorrect voice clip when switching inner cyclotron switch panel modes
-Fixed wand vibration motor having incorrect base frequency
-Fixed wand vibration starting before pack starts if "Vibrate Always" was enabled
-Fixed wands without 28-segment bargraphs failing to play bootup sound in Mode Original
-Fixed web interface allowing save to EEPROM without first saving settings
-Fixed web interface allowing users to click update settings if pack or wand are on
-Fixed web interface losing ability to vent if user shut pack off during vent sequence
-Fixed web interface not popping any confirmation prompt when changing settings that require rebooting the ESP32
-Fixed web interface pack setting for default startup volume affecting current volume instead
-Fixed web interface power reading not displaying zeroes after the decimal point
-Many "under the hood" fixes and optimizations
 
New Features:
 
-Added ability to disable cyclotron fade effect in 84/89
-Added ability to invert the power cell animation (support GPStar 1984 Power Cell)
-Added barrel retraction sound
-Added Halloween holiday firing mode
-Added new cyclotron ring simulation to improve roundness at low speeds
-Added new Frozen Empire ion arm startup and idle loop sounds
-Added new Boson Dart, button mash, and meson mode switch sounds courtesy of ProtonCharging
-Added POST animation for inner cyclotron cake and inner cyclotron switch panel
-Added support for GPStar 7-LED Jewel for cyclotron and barrel of Single Shot Blaster
-Added support for motorized inner or outer cyclotron
-Added 64-bit Windows version of GPStar Audio Firmware Flasher
-Greatly reduced sound effect filesize without affecting sound quality
-Made the 15-LED power cell and 36-LED outer cyclotron default if not using Lite kit
-Updated 3D print files for 1984 Power Cell and Spirit Outer Cyclotron LEDs
-Updated documentation
-Updated web interface
 
This release requires updating ALL devices (pack, wand, wireless/attenuator, single shot blaster) and updating your SD cards.

There are of course new sounds associated with this release, and all sounds for the pack and wand now exist in a "pack-wand" subfolder.
 
Additionally this release includes new firmware (v1.03) for the GPStar Audio boards. It is highly recommended to flash the new firmware to resolve volume issues and improve audio quality.

### CODE REVIEW

**Comment by nomakewan** [comment]
Just as a heads up, I'm still working on some outer cyclotron LED stuff on my end, and the docs need a once-over to try to prune out as much legacy stuff as possible. Plus we should really consider adding RADisLAB's programming port Etsy page to our recommendations for easy software updating (which also would resolve discussion #23 ) and consider a mention about how to add a switch to disable the 5V and 12V power to the GPStar equipment while charging (which would resolve discussion #20 ).

**Comment by DustinGrau** [comment]
Just updated/cleaned some of the docs regarding device flashing, and added the link to the RADisLAB product page with a note there is a programming cable recommended as part of that addon.

**Comment by DustinGrau** [comment]
Added the "Charging Switch" idea to the POWER.md guide

**Comment by DustinGrau** [comment]
That's all I can do this morning, but if you have more info about what Legacy stuff needs to be scubbed from docs I can help with that. And the only real purpose for the draft PR was to make code review easier. I can now see there are over 100 files changed, but I can begin to review and mark them as viewed as I get to them.

**Comment by nomakewan** [comment]
No worries! Just wanted to make sure everyone was aware of what was going on behind-the-scenes on my end.

Speaking of which, I've gotten the cyclotron ring simulation code all updated for the current version of the Proton Pack code, and tested it. It does work, but it needs some fine tuning (for example, for some strange reason it's faster going counter-clockwise than going clockwise). Once that fine-tuning is done I can push the ring sim update (finally!).

Then I'll be updating a few sound effects, fixing a few other miscellaneous bugs I found while testing the ring sim, and implementing the cyclotron spin motor code. With luck all of that will be done this weekend.

Excellent work so far!

**Review by nomakewan — APPROVED** [review]
Looks great on my ESP32, pack board, and wand board.

Only thing I haven't tested is the full integration (I haven't set up enough space to hook my bench pack to my wand), and there are some audio-related fixes that might be worth doing. However, as per our discussion this morning, audio changes can happen after the firmware is released via the support page.

So, putting my stamp of appoval on this one!

**Pull request merged**
